### ISSUE TITLE
Regression: Code does not compile due to undefined symbols

### ISSUE THREAD

**Issue by edbennett** [LupoA/Grid#15]
Commit `88bdd434` could be compiled (once the typo in `configure.ac` had been fixed). The current commit `8c80f1c` fails with undefined symbols like `__T0` and `__T1`. I'll try and collect some more detail and update once I have it.

**Comment by LupoA** [comment]
It seems to me it works using clang 4.2.1, although now I must specify c++14

**Comment by edbennett** [comment]
```
/mnt/lustre/tursafs1/home/dp208/dp208/shared/src/grid-sp4-20221213/Grid/qcd/utils/SUn.h: In static member function ‘static void Grid::GaugeGroup<ncolour, group_name>::su2Extract(Grid::Lattice<Grid::iScalar<Grid::iScalar<Grid::iScalar<ttype> > > >&, Grid::Lattice<Grid::iScalar<Grid::iScalar<Grid::iMatrix<vtype, 2> > > >&, const Grid::Lattice<Grid::iScalar<Grid::iScalar<Grid::iMatrix<vtype, ncolour> > > >&, int)’:
/mnt/lustre/tursafs1/home/dp208/dp208/shared/src/grid-sp4-20221213/Grid/qcd/utils/SUn.h:144:320: error: ‘__T0’ was not declared in this scope; did you mean ‘__y0’?
  144 |   accelerator_for(ss, grid->oSites(), 1, {
      |                                                                                                                                                                                                                                                                                                                                ^
      |                                                                                                                                                                                                                                                                                                                                __y0
/mnt/lustre/tursafs1/home/dp208/dp208/shared/src/grid-sp4-20221213/Grid/qcd/utils/SUn.h: In static member function ‘static void Grid::GaugeGroup<ncolour, group_name>::su2Insert(const Grid::Lattice<Grid::iScalar<Grid::iScalar<Grid::iMatrix<vtype, 2> > > >&, Grid::Lattice<Grid::iScalar<Grid::iScalar<Grid::iMatrix<vtype, ncolour> > > >&, int)’:
/mnt/lustre/tursafs1/home/dp208/dp208/shared/src/grid-sp4-20221213/Grid/qcd/utils/SUn.h:176:273: error: ‘__T1’ was not declared in this scope; did you mean ‘__y1’?
  176 |   accelerator_for(ss, grid->oSites(), 1, {
      |                                                                                                                                                                                                                                                                                 ^
      |                                                                                                                                                                                                                                                                                 __y1
```

**Comment by chillenzer** [comment]
Sorry, could you also give the compiler again? I think, `gcc9` was the underlying one, right?

**Comment by edbennett** [comment]
Module setup:

    module load gcc/9.3.0 cuda/11.4.1  openmpi/4.1.1-cuda11.4.1  ucx/1.12.0-cuda11.4.1

configure line:

    ../configure --prefix /home/dp208/dp208/dc-benn2/prefix-sp4-20221213 --enable-comms=mpi --enable-simd=GPU --enable-shm=nvlink --enable-gen-simd-width=64 --enable-accelerator=cuda --enable-Nc=4 --enable-accelerator-cshift --disable-unified --disable-gparity --with-lime=/home/dp208/dp208/dc-benn2/prefix CXX=nvcc LDFLAGS="-cudart shared" CXXFLAGS="-ccbin mpicxx -gencode arch=compute_80,code=sm_80 -std=c++14 -cudart shared"

**Comment by chillenzer** [comment]
Okay. Just reproduced the error on tursa. Have you seen [this](https://github.com/pytorch/pytorch/issues/3243) (and the links therein)? This error once appeared due to a mismatch between compiler and cuda version. Seems to be rather old and probably does not apply directly. I'm currently installing everything to reproduce locally and might be able to confirm or falsify this scenario.

**Comment by chillenzer** [comment]
Okay. Small update: [These](https://github.com/trilinos/Trilinos/issues/10285) [three](https://github.com/trilinos/Trilinos/pull/10272) [links](https://github.com/trilinos/Trilinos/pull/10272/commits/2efeffc19ce982ba1b7491d491a637b671c7e96b) seem to be more relevant but there is no explanation.

**Comment by chillenzer** [comment]
Found it! [This link](https://stackoverflow.com/questions/74349712/cuda-11-fails-to-compile-due-to-type-traits-in-standard-library-when-using-exten) tipped me off. There is a stupid little restriction in nvcc:
```
The template parameters must be named.
```
Which I haven't done for pure laziness because C++ does not require it usually. I will push a fix in a second. Could you please try if it works for you as well?

**Comment by edbennett** [comment]
Yep, that fixes it on my side as well. :+1:
